### ISSUE TITLE
Marketplace linked repository not available?

### ISSUE THREAD

**Issue by d-gomez** [jabiercoding/eclipaint#13]
Thanks for the useful tool. While reinstalling I found that install via marketplace does not work at the moment, https://raw.githubusercontent.com/jabiercoding/eclipaint/master/updatesite/org.eclipaint.site/ is not available.

Workaround is to check out the repository, in eclipse add a location pointing to the local repo .../updatesite/org.eclipaint.site with help/install new software.

**Comment by jabiercoding** [comment]
I cannot reproduce the issue... Can you try again? Maybe it was a temporary problem in marketplace server or in github server.

**Comment by d-gomez** [comment]
still there, checked with a fresh eclipse mars 2 x86:

![image](https://cloud.githubusercontent.com/assets/6737673/15418740/a98f23aa-1e61-11e6-84af-98d266d6b806.png)

first steps including license page are working.

**Comment by jabiercoding** [comment]
Thanks, I reproduced the issue. I will try to fix it.

As a temporary workaround (instead of check out the repo) it seems that it is possible to add this URL https://raw.githubusercontent.com/jabiercoding/eclipaint/master/updatesite/org.eclipaint.site/site.xml  (with the site.xml) in the help/install new software section.

**Comment by but4reuse** [comment]
Now it is working for me. 
I tried in a fresh mars and in a fresh neon. 
Apparently it takes time to update the changes of the marketplace information... The fix I think was the change I made pointing to site.xml instead to the update site folder. 

could you confirm using the marketplace? Thanks!

**Comment by jabiercoding** [comment]
Now it is working for me. 
I tried in a fresh mars and in a fresh neon. 
Apparently it takes time to update the changes of the marketplace information... The fix I think was the change I made pointing to site.xml instead to the update site folder.

could you confirm using the marketplace? Thanks!

**Comment by d-gomez** [comment]
yes, now it works.
